CREATE TABLE [NuFridge].[User] (
[Id] int IDENTITY(1,1) NOT NULL CONSTRAINT [PK_User_Id] PRIMARY KEY CLUSTERED,
[Username] NVARCHAR(100) NOT NULL,
[DisplayName] NVARCHAR(255) NOT NULL,
[EmailAddress] NVARCHAR(4000) NOT NULL,
[LastUpdated] DATETIME2 NOT NULL,
[IsActive] BIT NOT NULL,
[PasswordHashed] NVARCHAR(MAX) NOT NULL
)
ALTER TABLE [NuFridge].[User] ADD CONSTRAINT [UQ_UserUsernameUnique] UNIQUE([Username])