// <auto-generated />
namespace NuFridge.Service.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FeedPackageCleanerColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeedPackageCleanerColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201504200445443_FeedPackageCleanerColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
